/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as AuthLayoutRouteRouteImport } from './routes/_authLayout/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InvestorIndexRouteImport } from './routes/investor/index'
import { Route as ProtectedUtilitiesIndexRouteImport } from './routes/_protected/utilities/index'
import { Route as ProtectedUserManagementIndexRouteImport } from './routes/_protected/user-management/index'
import { Route as ProtectedSuppliersIndexRouteImport } from './routes/_protected/suppliers/index'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedOperatorIndexRouteImport } from './routes/_protected/operator/index'
import { Route as ProtectedHrIndexRouteImport } from './routes/_protected/hr/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as AuthLayoutSignUpIndexRouteImport } from './routes/_authLayout/sign-up/index'
import { Route as AuthLayoutResetPasswordIndexRouteImport } from './routes/_authLayout/reset-password/index'
import { Route as AuthLayoutLoginIndexRouteImport } from './routes/_authLayout/login/index'
import { Route as AuthLayoutForgotPasswordIndexRouteImport } from './routes/_authLayout/forgot-password/index'
import { Route as AuthLayout2FaIndexRouteImport } from './routes/_authLayout/2-fa/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedSuppliersSupplierIdRouteImport } from './routes/_protected/suppliers/$supplierId'
import { Route as ProtectedOperatorRunIdRouteImport } from './routes/_protected/operator/$runId'
import { Route as ProtectedSalesNewInvoiceIndexRouteImport } from './routes/_protected/sales/new-invoice/index'
import { Route as ProtectedSalesCustomersIndexRouteImport } from './routes/_protected/sales/customers/index'
import { Route as ProtectedManufacturingRecipesIndexRouteImport } from './routes/_protected/manufacturing/recipes/index'
import { Route as ProtectedManufacturingProductionsIndexRouteImport } from './routes/_protected/manufacturing/productions/index'
import { Route as ProtectedInventoryWarehousesIndexRouteImport } from './routes/_protected/inventory/warehouses/index'
import { Route as ProtectedInventoryFactoryFloorIndexRouteImport } from './routes/_protected/inventory/factory-floor/index'
import { Route as ProtectedManufacturingRecipesRecipeIdRouteImport } from './routes/_protected/manufacturing/recipes/$recipeId'
import { Route as ProtectedManufacturingProductionsRunIdRouteImport } from './routes/_protected/manufacturing/productions/$runId'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRouteRoute = AuthLayoutRouteRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorIndexRoute = InvestorIndexRouteImport.update({
  id: '/investor/',
  path: '/investor/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedUtilitiesIndexRoute = ProtectedUtilitiesIndexRouteImport.update({
  id: '/utilities/',
  path: '/utilities/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedUserManagementIndexRoute =
  ProtectedUserManagementIndexRouteImport.update({
    id: '/user-management/',
    path: '/user-management/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSuppliersIndexRoute = ProtectedSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedOperatorIndexRoute = ProtectedOperatorIndexRouteImport.update({
  id: '/operator/',
  path: '/operator/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedHrIndexRoute = ProtectedHrIndexRouteImport.update({
  id: '/hr/',
  path: '/hr/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const AuthLayoutSignUpIndexRoute = AuthLayoutSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const AuthLayoutResetPasswordIndexRoute =
  AuthLayoutResetPasswordIndexRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => AuthLayoutRouteRoute,
  } as any)
const AuthLayoutLoginIndexRoute = AuthLayoutLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const AuthLayoutForgotPasswordIndexRoute =
  AuthLayoutForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => AuthLayoutRouteRoute,
  } as any)
const AuthLayout2FaIndexRoute = AuthLayout2FaIndexRouteImport.update({
  id: '/2-fa/',
  path: '/2-fa/',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSuppliersSupplierIdRoute =
  ProtectedSuppliersSupplierIdRouteImport.update({
    id: '/suppliers/$supplierId',
    path: '/suppliers/$supplierId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedOperatorRunIdRoute = ProtectedOperatorRunIdRouteImport.update({
  id: '/operator/$runId',
  path: '/operator/$runId',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedSalesNewInvoiceIndexRoute =
  ProtectedSalesNewInvoiceIndexRouteImport.update({
    id: '/sales/new-invoice/',
    path: '/sales/new-invoice/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedSalesCustomersIndexRoute =
  ProtectedSalesCustomersIndexRouteImport.update({
    id: '/sales/customers/',
    path: '/sales/customers/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedManufacturingRecipesIndexRoute =
  ProtectedManufacturingRecipesIndexRouteImport.update({
    id: '/manufacturing/recipes/',
    path: '/manufacturing/recipes/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedManufacturingProductionsIndexRoute =
  ProtectedManufacturingProductionsIndexRouteImport.update({
    id: '/manufacturing/productions/',
    path: '/manufacturing/productions/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedInventoryWarehousesIndexRoute =
  ProtectedInventoryWarehousesIndexRouteImport.update({
    id: '/inventory/warehouses/',
    path: '/inventory/warehouses/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedInventoryFactoryFloorIndexRoute =
  ProtectedInventoryFactoryFloorIndexRouteImport.update({
    id: '/inventory/factory-floor/',
    path: '/inventory/factory-floor/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedManufacturingRecipesRecipeIdRoute =
  ProtectedManufacturingRecipesRecipeIdRouteImport.update({
    id: '/manufacturing/recipes/$recipeId',
    path: '/manufacturing/recipes/$recipeId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedManufacturingProductionsRunIdRoute =
  ProtectedManufacturingProductionsRunIdRouteImport.update({
    id: '/manufacturing/productions/$runId',
    path: '/manufacturing/productions/$runId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/investor/': typeof InvestorIndexRoute
  '/operator/$runId': typeof ProtectedOperatorRunIdRoute
  '/suppliers/$supplierId': typeof ProtectedSuppliersSupplierIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/2-fa/': typeof AuthLayout2FaIndexRoute
  '/forgot-password/': typeof AuthLayoutForgotPasswordIndexRoute
  '/login/': typeof AuthLayoutLoginIndexRoute
  '/reset-password/': typeof AuthLayoutResetPasswordIndexRoute
  '/sign-up/': typeof AuthLayoutSignUpIndexRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/hr/': typeof ProtectedHrIndexRoute
  '/operator/': typeof ProtectedOperatorIndexRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/suppliers/': typeof ProtectedSuppliersIndexRoute
  '/user-management/': typeof ProtectedUserManagementIndexRoute
  '/utilities/': typeof ProtectedUtilitiesIndexRoute
  '/manufacturing/productions/$runId': typeof ProtectedManufacturingProductionsRunIdRoute
  '/manufacturing/recipes/$recipeId': typeof ProtectedManufacturingRecipesRecipeIdRoute
  '/inventory/factory-floor/': typeof ProtectedInventoryFactoryFloorIndexRoute
  '/inventory/warehouses/': typeof ProtectedInventoryWarehousesIndexRoute
  '/manufacturing/productions/': typeof ProtectedManufacturingProductionsIndexRoute
  '/manufacturing/recipes/': typeof ProtectedManufacturingRecipesIndexRoute
  '/sales/customers/': typeof ProtectedSalesCustomersIndexRoute
  '/sales/new-invoice/': typeof ProtectedSalesNewInvoiceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/investor': typeof InvestorIndexRoute
  '/operator/$runId': typeof ProtectedOperatorRunIdRoute
  '/suppliers/$supplierId': typeof ProtectedSuppliersSupplierIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/2-fa': typeof AuthLayout2FaIndexRoute
  '/forgot-password': typeof AuthLayoutForgotPasswordIndexRoute
  '/login': typeof AuthLayoutLoginIndexRoute
  '/reset-password': typeof AuthLayoutResetPasswordIndexRoute
  '/sign-up': typeof AuthLayoutSignUpIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/hr': typeof ProtectedHrIndexRoute
  '/operator': typeof ProtectedOperatorIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/suppliers': typeof ProtectedSuppliersIndexRoute
  '/user-management': typeof ProtectedUserManagementIndexRoute
  '/utilities': typeof ProtectedUtilitiesIndexRoute
  '/manufacturing/productions/$runId': typeof ProtectedManufacturingProductionsRunIdRoute
  '/manufacturing/recipes/$recipeId': typeof ProtectedManufacturingRecipesRecipeIdRoute
  '/inventory/factory-floor': typeof ProtectedInventoryFactoryFloorIndexRoute
  '/inventory/warehouses': typeof ProtectedInventoryWarehousesIndexRoute
  '/manufacturing/productions': typeof ProtectedManufacturingProductionsIndexRoute
  '/manufacturing/recipes': typeof ProtectedManufacturingRecipesIndexRoute
  '/sales/customers': typeof ProtectedSalesCustomersIndexRoute
  '/sales/new-invoice': typeof ProtectedSalesNewInvoiceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authLayout': typeof AuthLayoutRouteRouteWithChildren
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/investor/': typeof InvestorIndexRoute
  '/_protected/operator/$runId': typeof ProtectedOperatorRunIdRoute
  '/_protected/suppliers/$supplierId': typeof ProtectedSuppliersSupplierIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authLayout/2-fa/': typeof AuthLayout2FaIndexRoute
  '/_authLayout/forgot-password/': typeof AuthLayoutForgotPasswordIndexRoute
  '/_authLayout/login/': typeof AuthLayoutLoginIndexRoute
  '/_authLayout/reset-password/': typeof AuthLayoutResetPasswordIndexRoute
  '/_authLayout/sign-up/': typeof AuthLayoutSignUpIndexRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/hr/': typeof ProtectedHrIndexRoute
  '/_protected/operator/': typeof ProtectedOperatorIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/suppliers/': typeof ProtectedSuppliersIndexRoute
  '/_protected/user-management/': typeof ProtectedUserManagementIndexRoute
  '/_protected/utilities/': typeof ProtectedUtilitiesIndexRoute
  '/_protected/manufacturing/productions/$runId': typeof ProtectedManufacturingProductionsRunIdRoute
  '/_protected/manufacturing/recipes/$recipeId': typeof ProtectedManufacturingRecipesRecipeIdRoute
  '/_protected/inventory/factory-floor/': typeof ProtectedInventoryFactoryFloorIndexRoute
  '/_protected/inventory/warehouses/': typeof ProtectedInventoryWarehousesIndexRoute
  '/_protected/manufacturing/productions/': typeof ProtectedManufacturingProductionsIndexRoute
  '/_protected/manufacturing/recipes/': typeof ProtectedManufacturingRecipesIndexRoute
  '/_protected/sales/customers/': typeof ProtectedSalesCustomersIndexRoute
  '/_protected/sales/new-invoice/': typeof ProtectedSalesNewInvoiceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/investor/'
    | '/operator/$runId'
    | '/suppliers/$supplierId'
    | '/api/auth/$'
    | '/2-fa/'
    | '/forgot-password/'
    | '/login/'
    | '/reset-password/'
    | '/sign-up/'
    | '/dashboard/'
    | '/hr/'
    | '/operator/'
    | '/settings/'
    | '/suppliers/'
    | '/user-management/'
    | '/utilities/'
    | '/manufacturing/productions/$runId'
    | '/manufacturing/recipes/$recipeId'
    | '/inventory/factory-floor/'
    | '/inventory/warehouses/'
    | '/manufacturing/productions/'
    | '/manufacturing/recipes/'
    | '/sales/customers/'
    | '/sales/new-invoice/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/investor'
    | '/operator/$runId'
    | '/suppliers/$supplierId'
    | '/api/auth/$'
    | '/2-fa'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/sign-up'
    | '/dashboard'
    | '/hr'
    | '/operator'
    | '/settings'
    | '/suppliers'
    | '/user-management'
    | '/utilities'
    | '/manufacturing/productions/$runId'
    | '/manufacturing/recipes/$recipeId'
    | '/inventory/factory-floor'
    | '/inventory/warehouses'
    | '/manufacturing/productions'
    | '/manufacturing/recipes'
    | '/sales/customers'
    | '/sales/new-invoice'
  id:
    | '__root__'
    | '/'
    | '/_authLayout'
    | '/_protected'
    | '/investor/'
    | '/_protected/operator/$runId'
    | '/_protected/suppliers/$supplierId'
    | '/api/auth/$'
    | '/_authLayout/2-fa/'
    | '/_authLayout/forgot-password/'
    | '/_authLayout/login/'
    | '/_authLayout/reset-password/'
    | '/_authLayout/sign-up/'
    | '/_protected/dashboard/'
    | '/_protected/hr/'
    | '/_protected/operator/'
    | '/_protected/settings/'
    | '/_protected/suppliers/'
    | '/_protected/user-management/'
    | '/_protected/utilities/'
    | '/_protected/manufacturing/productions/$runId'
    | '/_protected/manufacturing/recipes/$recipeId'
    | '/_protected/inventory/factory-floor/'
    | '/_protected/inventory/warehouses/'
    | '/_protected/manufacturing/productions/'
    | '/_protected/manufacturing/recipes/'
    | '/_protected/sales/customers/'
    | '/_protected/sales/new-invoice/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLayoutRouteRoute: typeof AuthLayoutRouteRouteWithChildren
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  InvestorIndexRoute: typeof InvestorIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor/': {
      id: '/investor/'
      path: '/investor'
      fullPath: '/investor/'
      preLoaderRoute: typeof InvestorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/utilities/': {
      id: '/_protected/utilities/'
      path: '/utilities'
      fullPath: '/utilities/'
      preLoaderRoute: typeof ProtectedUtilitiesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/user-management/': {
      id: '/_protected/user-management/'
      path: '/user-management'
      fullPath: '/user-management/'
      preLoaderRoute: typeof ProtectedUserManagementIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/suppliers/': {
      id: '/_protected/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof ProtectedSuppliersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/operator/': {
      id: '/_protected/operator/'
      path: '/operator'
      fullPath: '/operator/'
      preLoaderRoute: typeof ProtectedOperatorIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/hr/': {
      id: '/_protected/hr/'
      path: '/hr'
      fullPath: '/hr/'
      preLoaderRoute: typeof ProtectedHrIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_authLayout/sign-up/': {
      id: '/_authLayout/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof AuthLayoutSignUpIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/reset-password/': {
      id: '/_authLayout/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof AuthLayoutResetPasswordIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/login/': {
      id: '/_authLayout/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof AuthLayoutLoginIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/forgot-password/': {
      id: '/_authLayout/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof AuthLayoutForgotPasswordIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/_authLayout/2-fa/': {
      id: '/_authLayout/2-fa/'
      path: '/2-fa'
      fullPath: '/2-fa/'
      preLoaderRoute: typeof AuthLayout2FaIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/suppliers/$supplierId': {
      id: '/_protected/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof ProtectedSuppliersSupplierIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/operator/$runId': {
      id: '/_protected/operator/$runId'
      path: '/operator/$runId'
      fullPath: '/operator/$runId'
      preLoaderRoute: typeof ProtectedOperatorRunIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/new-invoice/': {
      id: '/_protected/sales/new-invoice/'
      path: '/sales/new-invoice'
      fullPath: '/sales/new-invoice/'
      preLoaderRoute: typeof ProtectedSalesNewInvoiceIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/sales/customers/': {
      id: '/_protected/sales/customers/'
      path: '/sales/customers'
      fullPath: '/sales/customers/'
      preLoaderRoute: typeof ProtectedSalesCustomersIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/manufacturing/recipes/': {
      id: '/_protected/manufacturing/recipes/'
      path: '/manufacturing/recipes'
      fullPath: '/manufacturing/recipes/'
      preLoaderRoute: typeof ProtectedManufacturingRecipesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/manufacturing/productions/': {
      id: '/_protected/manufacturing/productions/'
      path: '/manufacturing/productions'
      fullPath: '/manufacturing/productions/'
      preLoaderRoute: typeof ProtectedManufacturingProductionsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/inventory/warehouses/': {
      id: '/_protected/inventory/warehouses/'
      path: '/inventory/warehouses'
      fullPath: '/inventory/warehouses/'
      preLoaderRoute: typeof ProtectedInventoryWarehousesIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/inventory/factory-floor/': {
      id: '/_protected/inventory/factory-floor/'
      path: '/inventory/factory-floor'
      fullPath: '/inventory/factory-floor/'
      preLoaderRoute: typeof ProtectedInventoryFactoryFloorIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/manufacturing/recipes/$recipeId': {
      id: '/_protected/manufacturing/recipes/$recipeId'
      path: '/manufacturing/recipes/$recipeId'
      fullPath: '/manufacturing/recipes/$recipeId'
      preLoaderRoute: typeof ProtectedManufacturingRecipesRecipeIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/manufacturing/productions/$runId': {
      id: '/_protected/manufacturing/productions/$runId'
      path: '/manufacturing/productions/$runId'
      fullPath: '/manufacturing/productions/$runId'
      preLoaderRoute: typeof ProtectedManufacturingProductionsRunIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface AuthLayoutRouteRouteChildren {
  AuthLayout2FaIndexRoute: typeof AuthLayout2FaIndexRoute
  AuthLayoutForgotPasswordIndexRoute: typeof AuthLayoutForgotPasswordIndexRoute
  AuthLayoutLoginIndexRoute: typeof AuthLayoutLoginIndexRoute
  AuthLayoutResetPasswordIndexRoute: typeof AuthLayoutResetPasswordIndexRoute
  AuthLayoutSignUpIndexRoute: typeof AuthLayoutSignUpIndexRoute
}

const AuthLayoutRouteRouteChildren: AuthLayoutRouteRouteChildren = {
  AuthLayout2FaIndexRoute: AuthLayout2FaIndexRoute,
  AuthLayoutForgotPasswordIndexRoute: AuthLayoutForgotPasswordIndexRoute,
  AuthLayoutLoginIndexRoute: AuthLayoutLoginIndexRoute,
  AuthLayoutResetPasswordIndexRoute: AuthLayoutResetPasswordIndexRoute,
  AuthLayoutSignUpIndexRoute: AuthLayoutSignUpIndexRoute,
}

const AuthLayoutRouteRouteWithChildren = AuthLayoutRouteRoute._addFileChildren(
  AuthLayoutRouteRouteChildren,
)

interface ProtectedRouteRouteChildren {
  ProtectedOperatorRunIdRoute: typeof ProtectedOperatorRunIdRoute
  ProtectedSuppliersSupplierIdRoute: typeof ProtectedSuppliersSupplierIdRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedHrIndexRoute: typeof ProtectedHrIndexRoute
  ProtectedOperatorIndexRoute: typeof ProtectedOperatorIndexRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
  ProtectedSuppliersIndexRoute: typeof ProtectedSuppliersIndexRoute
  ProtectedUserManagementIndexRoute: typeof ProtectedUserManagementIndexRoute
  ProtectedUtilitiesIndexRoute: typeof ProtectedUtilitiesIndexRoute
  ProtectedManufacturingProductionsRunIdRoute: typeof ProtectedManufacturingProductionsRunIdRoute
  ProtectedManufacturingRecipesRecipeIdRoute: typeof ProtectedManufacturingRecipesRecipeIdRoute
  ProtectedInventoryFactoryFloorIndexRoute: typeof ProtectedInventoryFactoryFloorIndexRoute
  ProtectedInventoryWarehousesIndexRoute: typeof ProtectedInventoryWarehousesIndexRoute
  ProtectedManufacturingProductionsIndexRoute: typeof ProtectedManufacturingProductionsIndexRoute
  ProtectedManufacturingRecipesIndexRoute: typeof ProtectedManufacturingRecipesIndexRoute
  ProtectedSalesCustomersIndexRoute: typeof ProtectedSalesCustomersIndexRoute
  ProtectedSalesNewInvoiceIndexRoute: typeof ProtectedSalesNewInvoiceIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedOperatorRunIdRoute: ProtectedOperatorRunIdRoute,
  ProtectedSuppliersSupplierIdRoute: ProtectedSuppliersSupplierIdRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedHrIndexRoute: ProtectedHrIndexRoute,
  ProtectedOperatorIndexRoute: ProtectedOperatorIndexRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  ProtectedSuppliersIndexRoute: ProtectedSuppliersIndexRoute,
  ProtectedUserManagementIndexRoute: ProtectedUserManagementIndexRoute,
  ProtectedUtilitiesIndexRoute: ProtectedUtilitiesIndexRoute,
  ProtectedManufacturingProductionsRunIdRoute:
    ProtectedManufacturingProductionsRunIdRoute,
  ProtectedManufacturingRecipesRecipeIdRoute:
    ProtectedManufacturingRecipesRecipeIdRoute,
  ProtectedInventoryFactoryFloorIndexRoute:
    ProtectedInventoryFactoryFloorIndexRoute,
  ProtectedInventoryWarehousesIndexRoute:
    ProtectedInventoryWarehousesIndexRoute,
  ProtectedManufacturingProductionsIndexRoute:
    ProtectedManufacturingProductionsIndexRoute,
  ProtectedManufacturingRecipesIndexRoute:
    ProtectedManufacturingRecipesIndexRoute,
  ProtectedSalesCustomersIndexRoute: ProtectedSalesCustomersIndexRoute,
  ProtectedSalesNewInvoiceIndexRoute: ProtectedSalesNewInvoiceIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLayoutRouteRoute: AuthLayoutRouteRouteWithChildren,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  InvestorIndexRoute: InvestorIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
